# Generated by Django 4.2.4 on 2023-09-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=6, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("expiration_date", models.DateField()),
                (
                    "customer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
    ]
