# Generated by Django 4.2.4 on 2023-09-03 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon_burner_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="discount",
            field=models.CharField(
                blank=True,
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_discount",
                        message="Discount must be between 1% and 100%.",
                        regex="^(100|[1-9][0-9]|[1-9])%$",
                    )
                ],
            ),
        ),
    ]
