# Generated by Django 4.2.4 on 2023-09-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon_burner_app", "0002_coupon_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
