# Generated by Django 4.2.4 on 2023-09-03 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("coupon_burner_app", "0003_alter_coupon_customer_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
