# Generated by Django 4.2.4 on 2023-09-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon_burner_app", "0004_coupon_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
