# Generated by Django 4.2.4 on 2023-09-03 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon_burner_app", "0005_alter_coupon_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="expiration_date",
            field=models.DateField(default=datetime.date(2023, 10, 3)),
        ),
    ]
